"""add llm call logs

Revision ID: ca4b5ef851cd
Revises: b7c8d9e0f1a2
Create Date: 2026-04-22 18:42:08.562908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca4b5ef851cd'
down_revision: Union[str, None] = 'b7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_call_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('call_type', sa.Enum('CHAT', 'VISION', 'EMBED', name='llmcalltype'), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('response_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'ERROR', name='llmcallstatus'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('teaching_session_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teaching_session_id'], ['teaching_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_call_logs_call_type_created_at', 'llm_call_logs', ['call_type', 'created_at'], unique=False)
    op.create_index('ix_llm_call_logs_status_created_at', 'llm_call_logs', ['status', 'created_at'], unique=False)
    op.create_index('ix_llm_call_logs_student_id', 'llm_call_logs', ['student_id'], unique=False)
    op.create_index('ix_llm_call_logs_teaching_session_id', 'llm_call_logs', ['teaching_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_llm_call_logs_teaching_session_id', table_name='llm_call_logs')
    op.drop_index('ix_llm_call_logs_student_id', table_name='llm_call_logs')
    op.drop_index('ix_llm_call_logs_status_created_at', table_name='llm_call_logs')
    op.drop_index('ix_llm_call_logs_call_type_created_at', table_name='llm_call_logs')
    op.drop_table('llm_call_logs')
    sa.Enum(name='llmcallstatus').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='llmcalltype').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
