"""add questions table

Revision ID: e7d70f5c07d5
Revises: 43a906f5a39f
Create Date: 2026-04-21 18:56:56.451682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = 'e7d70f5c07d5'
down_revision: Union[str, None] = '43a906f5a39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'FILL_BLANK', 'SHORT_ANSWER', 'CALCULATION', name='questiontype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_image', sa.String(length=500), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('answer_image', sa.String(length=500), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('analysis_image', sa.String(length=500), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_questions_difficulty', 'questions', ['difficulty'], unique=False)
    op.create_index('ix_questions_type', 'questions', ['type'], unique=False)
    op.create_table('question_knowledge_points',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'section_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_knowledge_points')
    op.drop_index('ix_questions_type', table_name='questions')
    op.drop_index('ix_questions_difficulty', table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
